version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_DB_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      - mysqldb
    image: book-store
    restart: unless-stopped
    build: .
    env_file:
      - ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DB_DOCKER_PORT/$DATABASE_NAME?serverTimezone=UTC",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
